---
baseurl: "https://blog.codeaddict.org/"
languageCode: "en-us"
title: "c0deaddict"
languagecode: "en-EN"
metaDataFormat: "yaml"
theme: "hyde"
paginate: 10
paginatePath: "page"
disqusShortname: "c0deaddict"

permalinks:
  post: "/:year/:month/:day/:slug/"
  code: "/:slug/"

taxonomies:
  tags: "tags"
  topic: "topics"

author:
  name: "Jos van Bakel"
  email: "jos@codeaddict.org"

params:
  description: "Random musings mostly about IT"
  themeColor: "theme-base-0d"

Menus:
  main:
    - Name: "About"
      URL: "/about/"
    - Name: "Github"
      URL: "https://github.com/c0deaddict"
    - Name: "LinkedIn"
      URL: "https://linkedin.com/in/josvanbakel"
    - Name: "Twitter"
      URL: "https://twitter.com/c0deaddict"
